"""IATA airport code → canonical city lookup."""

# ~200 most common codes, plus all codes seen in Matt's emails
IATA_TO_CITY = {
    # --- North America ---
    "JFK": "New York", "EWR": "New York", "LGA": "New York",
    "LAX": "Los Angeles", "BUR": "Los Angeles",
    "SFO": "San Francisco", "OAK": "San Francisco",
    "ORD": "Chicago", "MDW": "Chicago",
    "ATL": "Atlanta",
    "DFW": "Dallas", "DAL": "Dallas",
    "IAH": "Houston", "HOU": "Houston",
    "DEN": "Denver",
    "SEA": "Seattle",
    "MIA": "Miami", "FLL": "Fort Lauderdale",
    "BOS": "Boston",
    "PHL": "Philadelphia",
    "MSP": "Minneapolis",
    "DTW": "Detroit",
    "CLT": "Charlotte",
    "PHX": "Phoenix",
    "SLC": "Salt Lake City",
    "SAN": "San Diego",
    "TPA": "Tampa",
    "MCO": "Orlando",
    "BWI": "Baltimore",
    "IAD": "Washington DC", "DCA": "Washington DC",
    "PDX": "Portland",
    "AUS": "Austin",
    "BNA": "Nashville",
    "SMF": "Sacramento",
    "SNA": "Orange County",
    "RDU": "Raleigh",
    "IND": "Indianapolis",
    "MCI": "Kansas City",
    "CMH": "Columbus",
    "STL": "St. Louis",
    "PIT": "Pittsburgh",
    "MKE": "Milwaukee",
    "OKC": "Oklahoma City",
    "SAT": "San Antonio",
    "ABQ": "Albuquerque",
    "AMA": "Amarillo",
    "LIR": "Liberia",  # Costa Rica
    "SJO": "San Jose",  # Costa Rica
    "CUN": "Cancun",
    "MEX": "Mexico City",
    "GDL": "Guadalajara",
    "YUL": "Montreal", "YYZ": "Toronto", "YVR": "Vancouver",
    # --- Europe ---
    "BCN": "Barcelona", "MAD": "Madrid", "AGP": "Malaga", "PMI": "Palma de Mallorca",
    "LHR": "London", "LGW": "London", "STN": "London", "LTN": "London",
    "CDG": "Paris", "ORY": "Paris",
    "FRA": "Frankfurt", "MUC": "Munich", "BER": "Berlin", "HAM": "Hamburg",
    "AMS": "Amsterdam",
    "FCO": "Rome", "MXP": "Milan", "VCE": "Venice", "NAP": "Naples",
    "LIS": "Lisbon", "OPO": "Porto",
    "DUB": "Dublin",
    "ZRH": "Zurich", "GVA": "Geneva",
    "VIE": "Vienna",
    "BRU": "Brussels",
    "CPH": "Copenhagen",
    "OSL": "Oslo",
    "ARN": "Stockholm",
    "HEL": "Helsinki",
    "ATH": "Athens",
    "IST": "Istanbul", "SAW": "Istanbul",
    "WAW": "Warsaw",
    "PRG": "Prague",
    "BUD": "Budapest",
    "OTP": "Bucharest",
    "MSQ": "Minsk",
    "SVO": "Moscow", "DME": "Moscow", "VKO": "Moscow",
    "LED": "St. Petersburg",
    "FUE": "Fuerteventura",
    "TFS": "Tenerife", "TFN": "Tenerife",
    "EDI": "Edinburgh",
    # --- Asia ---
    "NKG": "Nanjing",
    "PVG": "Shanghai", "SHA": "Shanghai",
    "PEK": "Beijing", "PKX": "Beijing",
    "HKG": "Hong Kong",
    "NRT": "Tokyo", "HND": "Tokyo",
    "ICN": "Seoul", "GMP": "Seoul",
    "SIN": "Singapore",
    "BKK": "Bangkok",
    "KUL": "Kuala Lumpur",
    "DEL": "Delhi",
    "BOM": "Mumbai",
    "BLR": "Bangalore",
    "GOI": "Goa",
    "DXB": "Dubai",
    "DOH": "Doha",
    "TLV": "Tel Aviv",
    # --- Oceania ---
    "SYD": "Sydney", "MEL": "Melbourne", "BNE": "Brisbane",
    "AKL": "Auckland",
    # --- South America ---
    "GRU": "Sao Paulo", "GIG": "Rio de Janeiro",
    "EZE": "Buenos Aires",
    "BOG": "Bogota",
    "LIM": "Lima",
    "SCL": "Santiago",
    # --- Africa ---
    "CPT": "Cape Town", "JNB": "Johannesburg",
    "CAI": "Cairo",
    "CMN": "Casablanca",
    "NBO": "Nairobi",
}


def iata_to_city(code: str) -> str:
    """Resolve an IATA code to a canonical city name. Returns empty string if unknown."""
    return IATA_TO_CITY.get(code.upper().strip(), "")
